MANIFEST_SCHEMA_VERSION = "1"
RUNTIME_API_VERSION = "1"
SDK_API_VERSION = "1"

MAX_INPUT_BYTES = 4096
MAX_OUTPUT_BYTES = 4096
MAX_NESTING_DEPTH = 5
MAX_CONTAINER_ITEMS = 32
MAX_TOTAL_NODES = 128
MAX_STRING_LENGTH = 1024
