REQUEST_ENVELOPE_ID = "semantic_request"
RESULT_ENVELOPE_ID = "semantic_result"
GENERATE_OPTIONS_TASK = "generate_options"
OPTION_SET_FAMILY = "option_set"
CONTRACT_VERSION = "1"
ACTIVE_LIFECYCLE = "active"
ADMITTED_LIFECYCLE_MODE = "validation"

MAX_REQUEST_BYTES = 16_384
MAX_RESULT_BYTES = 65_536
MAX_STRING_LENGTH = 2_048
MAX_LIST_ITEMS = 64
MAX_OBJECT_PROPERTIES = 32
MAX_NESTING_DEPTH = 8
MAX_TOTAL_NODES = 1_024
MAX_INTEGER_ABS = 9_007_199_254_740_991
MAX_OPTIONS = 8

SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
