from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS = 0
    INVALID_USAGE = 2
    INVALID_CONFIGURATION = 10
    INVALID_INPUT = 11
    UNKNOWN_COMMAND = 12
    PERMISSION_DENIED = 13
    EXECUTION_FAILURE = 20
    TIMEOUT = 21
    NOT_READY = 22
    CONFIRMATION_REQUIRED = 23
    RESTART_REQUIRED = 24
    INTERNAL_ERROR = 30
    WORKFLOW_NOT_FOUND = 31
    INVALID_WORKFLOW = 32
    UNSUPPORTED_WORKFLOW_VERSION = 33
    UNKNOWN_WORKFLOW_OPERATION = 34
    WORKFLOW_EXECUTION_FAILURE = 35
    WORKFLOW_TIMEOUT = 36
    WORKFLOW_INTERNAL_ERROR = 37
    INTERRUPTED = 130
