PROVIDER_MANIFEST_SCHEMA_VERSION = "1"
PROVIDER_API_VERSION = "1"

CLOCK_PROVIDER_TYPE = "clock"
LOCAL_CLOCK_IDENTITY = "system.clock.local"
LOCAL_CLOCK_IMPLEMENTATION_IDENTITY = "vss.local-clock"

STORYBOARD_RENDER_PROVIDER_TYPE = "storyboard_render"
LOCAL_STORYBOARD_RENDER_IDENTITY = "movie.storyboard-render.local"
LOCAL_STORYBOARD_RENDER_IMPLEMENTATION_IDENTITY = "vss.local-deterministic-storyboard-svg"
