name: ADR Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-adr:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Validate ADR documents
        run: |
          chmod +x scripts/validate_adr.sh
          ./scripts/validate_adr.sh
