name: Ansible Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  ansible-validation:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Ansible tools
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Debug Ansible configuration
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      run: |
        pwd
        ls -la
        ansible --version
        ansible-config dump --only-changed

    - name: Debug Ansible paths
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
        ANSIBLE_ROLES_PATH: ${{ github.workspace }}/ansible/roles
      run: |
        ansible --version
        ansible-config dump --only-changed
        ls -la ansible/roles
        ls -la ansible/roles/baseline

    - name: Ansible syntax check
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
        ANSIBLE_ROLES_PATH: ${{ github.workspace }}/ansible/roles
      run: |
        ansible-config dump --only-changed

        ansible-playbook \
          --syntax-check \
          -i ansible/inventories/development/hosts.yml \
          ansible/playbooks/site.yml

    - name: Ansible lint
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      run: |
        ansible-lint ansible/playbooks/site.yml
