name: Ansible Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  ansible-validation:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Ansible tools
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Debug Ansible configuration
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      run: |
        pwd
        ls -la
        ansible --version
        ansible-config dump --only-changed

    - name: Ansible syntax check
      run: |
        ansible-playbook \
          --syntax-check \
          -i localhost, \
          -c local \
          --roles-path ansible/roles \
          ansible/playbooks/site.yml`

    - name: Ansible lint
      env:
        ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      run: |
        ansible-lint ansible/playbooks/site.yml
